on: [push]
name: haskell-ci
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['8.8.4', '8.10.7', '9.2.1']
        os: [ubuntu-latest]
        manager: ['cabal']
        experimental: [false]
        include:
          - os: windows-latest
            ghc: '8.10.7'
            experimental: true
          - os: macOS-latest
            ghc: '8.10.7'
            experimental: true
          - os: ubuntu-latest
            ghc: '8.10.7'
            experimental: true
            manager: 'stack'
    continue-on-error: ${{ matrix.experimental }}
    name: ghc ${{ matrix.ghc }} ${{ matrix.os }} ${{ matrix.manager }}
    steps:
      - name: clone project
        uses: actions/checkout@v2
      - name: setup stanza
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: ${{ matrix.manager == 'stack' }}
          stack-version: 'latest'
      - name: cabal cache
        if: (matrix.manager == 'cabal')
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ github.sha }}
          path: ~/.cabal/store
          restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-
      - name: cabal build
        if: (matrix.manager == 'cabal')
        run: |
          cabal configure --enable-tests
          cabal build
          cabal test
      - name: stack cache
        if: (matrix.manager == 'stack')
        uses: actions/cache@v1
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}
          restore-keys: ${{ runner.os }}-
      - name: stack build
        if: (matrix.manager == 'stack')
        run: |
          stack update
          stack build --test --no-install-ghc --system-ghc
