on: [push]
name: haskell-ci
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['8.10.7']
        os: [ubuntu-latest]
        runstack: [false]
        runcabal: [true]
        experimental: [false]
    continue-on-error: ${{ matrix.experimental }}
    name: ghc ${{ matrix.ghc }} ${{ matrix.os }} stack ${{ matrix.stack }}
    steps:
      - name: clone project
        uses: actions/checkout@v2
      - name: setup stanza
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: ${{ matrix.stack }}
          stack-version: 'latest'
      - name: cabal cache
        if: matrix.runcabal
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ github.sha }}
          path: ~/.cabal/store
          restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-
      - name: cabal build
        if: matrix.runcabal
        run: |
          cabal configure --enable-tests
          cabal build
          cabal test
      - name: stack cache
        if: matrix.runstack
        uses: actions/cache@v1
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}
          restore-keys: ${{ runner.os }}-
      - name: stack build
        if: matrix.runstack
        run: |
          stack update
          stack build --test --no-install-ghc --system-ghc
