on: [push]
name: haskell-ci
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['8.8.4', '8.10.7', '9.2.1']
        os: [ubuntu-latest, macOS-latest, windows-latest]
        stack: [true, false]
    name: ghc ${{ matrix.ghc }} ${{ matrix.os }}
    steps:
      - name: clone project
        uses: actions/checkout@v2
